name: shelf_server
description: A server app using the shelf package and Docker.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.7.4 <3.0.0'


dependencies:
  args: ^2.0.0
  shelf: ^1.1.0
  shelf_router: ^1.0.0
  shelf_static: ^1.1.0
  mongo_dart: ^0.7.4
  crypto: ^3.0.1
  dart_jsonwebtoken: ^2.4.0
  redis: ^2.2.0
  dart_dotenv: ^1.0.1

dev_dependencies:
  http: ^0.13.0
  lints: ^1.0.0
  test_process: ^2.0.0
  test: ^1.15.0
